; Script generated by the HM NIS Edit Script Wizard.

!define APP_NAME "WhatsappRelay"
!define APP_VERSION "0.02"
!define INSTALL_DIR "$PROGRAMFILES\WhatsappRelay"

Name "${APP_NAME} ${APP_VERSION}"
OutFile "installer.exe"
InstallDir "${INSTALL_DIR}"

Section
SetOutPath "$INSTDIR"
File "installer.bat"
;File "additional_files\*.*" ; Include any additional files your script needs
SectionEnd
